### ISSUE TITLE
confusion definition of MSE and RMSE

### ISSUE THREAD

**Issue by thegodone** [YerevaNN/BARTSmiles#2]
I identify a bug in the code (it's a classical one indeed):

https://github.com/YerevaNN/BARTSmiles/blob/b02c261e048f06d6980922b10045b2939868db64/utils/utils.py#L15

you write mean_squared_error(true,pred), in sklearn this is MSE and not RMSE:
to get RMSE you must to set arg squared=False https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html

Can you also correct the values on your publication for all regression tasks ie np.sqrt(mse) another way to write it.
in table 4. a: last line must be corrected 
ESOL 0.095 (MSE) => 0.31 (RMSE)
Freesolv 0.114 (MSE)  => 0.34 (RMSE)
Liop 0.292 (MSE) => 0.54 (RMSE)
and avg column => 0.40
of course this affect the figure 1 too

**Comment by gayanechilingar** [comment]
Dear, thank you for the corrections. The bug is fixed now.
