### ISSUE TITLE
Install questions 

### ISSUE THREAD

**Issue by PatWalters** [YerevaNN/BARTSmiles#5]
There are a few things that are unclear in the installation instructions.

1. README.md says
Setup a conda environment:
conda create --name <env_name> --file examples/requirements.txt

Where is this requirements.txt?  I don't see anywhere in the repo 

2. Is Fairseq supposed to be installed under the root directory or the BARTsmiles directory? 
3. The  "Finetuning on MoleculeNet tasks section refers to "python process/process_datasets.py".  Should this be "python preprocess/process_datasets.py"? 

It would be helpful to see which directory each package should be installed into. 

Thanks for your help with this.

**Comment by kosonocky** [comment]
Yeah there is no environment.yml file to make the conda environment...

@gayanechilingar

**Comment by gayanechilingar** [comment]
Thank you for the questions and corrections.

1. I added the environment.yml file and changed the setup instructions in the README file.
2. Both BARTSmiles and Fairseq must be cloned into the root directory.
3. Yes, It should be  "python preprocess/process_datasets.py".

**Comment by PatWalters** [comment]
Thank you
